[package]
name = "frontend-estree"
version = "0.1.0"
authors = ["Bernard Teo <btzy1996@hotmail.com>"]
description = "Compiler frontend that converts ESTree to IR"
license = "MIT/Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
ir = { path = "../lib-ir" }
projstd = { path = "../lib-projstd" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
